wifi_ssid: !secret wifi_ssid
wifi_password: !secret wifi_password
esphome_ota_password: !secret esphome_ota_password
esphome_api_key: !secret esphome_api_key
victron_smartsolar_mac: "mppt key"
victron_smartsolar_bindkey: !secret victron_smartsolar_bindkey
wifi_ap_password: "ap_password"
